# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Publish

on: push
defaults:
  run:
    shell: bash # Run everything using bash

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Set up build environment
        run: |
          yarn

      - name: Build app
        run: |
          yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
